# À propos des auteurs {#auteurs .unnumbered}

[**Philippe Apparicio**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/philippe.apparicio) est professeur titulaire au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Transport et mobilité durable*, *Modélisation et analyse spatiale* et *Géomatique appliquée à la gestion urbaine*. Géographe de formation, ses intérêts de recherche incluent la justice et l'équité environnementale, la mobilité durable, les pollutions atmosphérique et sonore, et le vélo en ville. Il a publié une centaine d'articles scientifiques dans différents domaines des études urbaines et de la géographie mobilisant la géomatique et l'analyse spatiale.

[**Jean Dubé**](https://www.esad.ulaval.ca/personnel/professeurs/jean-dube) est professeur titulaire à l’[École Supérieure d’aménagement du territoire et de développement régional (ÉSAD)](https://www.esad.ulaval.ca/) de l'[Université Laval](https://www.ulaval.ca/). Économiste de formation, ses intérêts de recherche portent notamment sur l’évaluation d’impact des politiques publiques liées à l’aménagement et au développement. Ses recherches portent sur la mesure des externalités urbaines par le marché immobilier, les décisions de localisation des entreprises et des ménages et les déterminants de la croissance urbaine et régionale. Il est aussi rédacteur de la [Revue canadienne des sciences régionales (RCSR)](https://idjs.ca/fr/rcsr).

**Jérémy Gelb** a obtenu un doctorat en études urbaines à l'INRS en 2022 (*L'exposition des cyclistes aux pollutions atmosphérique et sonore en milieu urbain : comparaison empirique de plusieurs villes à travers le monde*), sous la supervision de Philippe Apparicio. Il utilise quotidiennement des systèmes d'information géographique (SIG) et des méthodes d'analyses spatiales. Il est tombé dans la marmite de l'*open source* avec le triptyque QGIS, R et Python au début de sa maîtrise. Il a développé deux *packages* : [`geocmeans`](https://cran.r-project.org/web/packages/geocmeans/index.html) et [`spNetwork`](https://cran.r-project.org/web/packages/spNetwork/index.html), permettant respectivement d'effectuer des analyses de classification floue non supervisée pondérée spatialement et des estimations de densité par kernel sur réseau. Il travaille actuellement comme conseiller en science des données à l'[Autorité régionale de transport métropolitain](https://www.artm.quebec/a-propos-de-l-artm/mission/) qui gère la planification du transport collectif dans la région de Montréal. Ces travaux portent sur la qualité des milieux urbains, l'accessibilité spatiale, le transport, l'équité environnementale, les SIG et l'analyse spatiale.


[**Joan Carles Martori**](https://urecerca.uvic.cat/CawDOS/jsf/seleccionActividades/seleccionActividades.jsf?id=276da803df40ac2c&idioma=ca&tipo=activ&elmeucv=N) est professeur d'économie appliquée au département d'économie et de commerce de l'[Université de Vic - Université centrale de la Catalogne](https://www.uvic.cat/fr) (Barcelone, Espagne). Il enseigne les statistiques appliquées et l'économétrie dans des cours de premier et de deuxième cycle. Il est le chercheur principal du groupe [Data Analysis and Modelling](https://mon.uvic.cat/dam/). Économiste de formation, ses recherches portent sur la ségrégation résidentielle, les inégalités et l'équité environnementale à l'aide des statistiques spatiales et de techniques économétriques. Il a contribué au développement du *package* R [`AQuadtree`](https://cran.r-project.org/web/packages/AQuadtree/index.html) sur la confidentialité des données spatiales ponctuelles. En tant que statisticien appliqué, il collabore avec d'autres disciplines telles que l'éducation et la santé.