project:
  type: book
  output-dir: docs
license: CC BY-SA
latex-auto-install: true

lang: fr
language:
  title-block-author-plural: "Auteurs"
  repo-action-links-issue: "Signaler un problème ou<br>formuler une suggestion"
crossref:
  fig-prefix: figure
  tbl-prefix: tableau
  sec-prefix: section
  eq-prefix: équation
  fig-title: Figure
  tbl-title: Tableau
  eq-title: Équation
book:
  title: 'Régressions spatiales : un grand bol d’R'
  search: true
  author: 
    - name: Philippe Apparicio
      url: https://www.usherbrooke.ca/recherche/fr/specialistes/details/philippe.apparicio
      affiliation: Département de géomatique appliquée<br>Université de Sherbrooke, Canada
      affiliation-url: https://www.usherbrooke.ca/geomatique/
    - name: Jean Dubé
      url: https://www.esad.ulaval.ca/personnel/professeurs/jean-dube
      affiliation: ÉSAD<br>Université Laval, Canada
      affiliation-url: https://www.ulaval.ca/
    - name: Jérémy Gelb
      url: https://scholar.google.com/citations?user=oFofDScAAAAJ&hl=fr
      affiliation: Autorité régionale de transport métropolitain<br>Montréal, Canada
      affiliation-url: https://www.artm.quebec/
    - name: Joan Carles Martori
      url: https://mon.uvic.cat/dam/
      affiliation: Département d'économie<br>Université de Vic, Espagne
      affiliation-url: https://mon.uvic.cat/
  date: today
  date-format: YYYY-MM-DD
  reader-mode: false
  page-footer:
    left: |
      Régressions spatiales : un grand bol d’R.
    right: |
      Ce livre a été réalisé avec <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/introduction/CouvertureP1.png
  favicon: images/introduction/CouvertureP1.png
  site-url: https://serieboldr.github.io/RegressionsSpatiales/index.html
  repo-url: https://github.com/SerieBoldR/RegressionsSpatiales
  repo-branch: main
  repo-actions:
  - issue
  # downloads: pdf
  chapters:
  - index.qmd
  - 00-auteurs.qmd
  - part: Partie 1. Notions de base
  - 01-NotionsDeBase.qmd
  - part: Partie 2. Économétrie spatiale
  - 02-ModelesEconometrieSpatiale.qmd
  - 03-ModelesSpatiauxPanel.qmd
  - part: Partie 3. Régressions géographiquement pondérées
  #- 04-GWRClassique.qmd
  - 05-GWRExtensions.qmd
  - part: Partie 4. Autres approches de modélisations spatiales
  - 06-GAM.qmd
  - 07-SEM.qmd
  - part: Partie 7. Exercices et bibliographie
  - 08-Exercices.qmd
  - references.qmd
      
bibliography: references.bib
csl: StyleRefs.csl

format:
  html:
    colorlinks: true
    css: css/quizlib.min.css
    theme:
      light:
      - cosmo
      - css/r4ds.scss
    code-link: true
    fontsize: 11pt
    mainfont: Helvetica Neue,Helvetica,Arial,sans-serif
    monofont: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace